#!/usr/bin/env bash

case `uname -s` in
    "Darwin")
        if ! which brew > /dev/null; then
            echo -e '### Installing Brew\n'
            /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
        if ! which pip > /dev/null; then
            brew install pip
        fi
        if ! which ansible-playbook > /dev/null; then
            echo -e '### Installing Ansible\n'
            sudo pip install -Iv ansible==2.2.1.0
        fi
        ;;
    "Linux")
        case `head -n 1 /etc/issue | cut -f 1 -d ' '` in
            "Debian")
                if ! which pip > /dev/null; then
                    sudo apt-get -y install python-pip
                fi
                if ! which ansible-playbook > /dev/null; then
                    echo -e '### Installing Ansible\n'
                    sudo pip install -Iv ansible==2.2.1.0
                fi
                ;;
            "CentOS")
                sudo yum install ansible
                ;;
        esac
        ;;
esac
